# Generated by Django 3.1 on 2020-08-28 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('user_filed', models.CharField(max_length=50)),
                ('status', models.CharField(default='New', max_length=50)),
                ('user_assigned', models.CharField(blank=True, max_length=50, null=True)),
                ('user_completed', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
