# Generated by Django 3.1 on 2020-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_filed',
            field=models.CharField(max_length=50),
        ),
    ]
